// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Shared._White.Bark;
using Content.Shared._White.CCVar;
using Content.Shared.CCVar;
using Content.Goobstation.Common.CCVar; // Goob Station - Barks, Voice chat
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Content.Shared._VDS.CCVars; // VDS

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private readonly IAudioManager _audio = default!;
    [Dependency] private readonly IClientAdminManager _admin = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        /* Reserve - use the other barks
        // Goob Station - Barks-start
        Control.AddOptionPercentSlider(
            GoobCVars.BarksVolume,
            SliderVolumeBarks,
            scale: ContentAudioSystem.BarksMultiplier);
        // Goob Station - Barks-end
        */

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        Control.AddOptionPercentSlider(
            GoobCVars.VoiceChatVolume,
            SliderVolumeVoiceChat,
            0, 2); // Goobstation - Voice chat

        // Reserve Station: WWDP port, Bark settings
        Control.AddOptionPercentSlider(
            WhiteCVars.BarkVolume,
            SliderVolumeBark,
            scale: ContentAudioSystem.BarkMultiplier);

        Control.AddOptionSlider(
            WhiteCVars.BarkLimit,
            SliderLimitBark,
            0,
            128);

        // Goobstation - Highlight Chat Ping/Audio!
        Control.AddOptionPercentSlider(
            CCVars.ChatHighlightVolume,
            SliderHighlightVolume,
            scale: 1f);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));

        Control.AddOptionCheckBox(GoobCVars.VoiceChatHearSelf, HearSelfCheckBox);
        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);

        // Reserve Station: WWDP port, Voice type dropdown
        Control.AddOptionDropDown(
            WhiteCVars.VoiceType,
            DropDownVoiceType,
            [
                new (CharacterVoiceType.None, Loc.GetString("char-voice-none")),
                new (CharacterVoiceType.Bark, Loc.GetString("char-voice-bark")),
            ]);

        // VDS start
        var acousticEnable = Control.AddOptionCheckBox(VCCVars.AcousticEnable, AcousticEnableCheckBox);
        acousticEnable.ImmediateValueChanged += UpdateAcousticButtons;
        Control.AddOptionCheckBox(VCCVars.AcousticHighResolution, AcousticHighResolutionCheckBox);
        Control.AddOptionSlider(
            VCCVars.AcousticReflectionCount,
            SliderAcousticReflectionCount,
            _cfg.GetCVar(VCCVars.AcousticReflectionCountMinimum),
            _cfg.GetCVar(VCCVars.AcousticReflectionCountMaximum));
        // VDS end

        Control.Initialize();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
        UpdateAcousticButtons(_cfg.GetCVar(VCCVars.AcousticEnable)); // VDS
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }


    private void UpdateAdminButtonsVisibility()
    {
        BwoinkSoundCheckBox.Visible = _admin.IsActive();
    }

    private void UpdateAcousticButtons(bool value) // VDS
    {
        AcousticHighResolutionCheckBox.Visible = value is true;
        SliderAcousticReflectionCount.Visible = value is true;
    }

    private void OnMasterVolumeSliderChanged(float value)
    {
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        _audio.SetMasterGain(value);
    }
}
