version = 1
SPDX-PackageName = "TarkovStation"
SPDX-PackageDownloadLocation = "https://github.com/ultradyper/TarkovStation"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"
