version = 1
SPDX-PackageName = "Reserve Station"
SPDX-PackageSupplier = "Ceterai <ceterai@protonmail.com>"
SPDX-PackageDownloadLocation = "https://ccdn.reserve-station.space/fork/reserve"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"
