// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._Shitcode.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ActionsTabControl : BaseTabControl
{
    // [Dependency] private readonly EntityManager _entManager = default!; // Reserve edit: Fix warnings
    // [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // Reserve edit: Fix warnings
    // [Dependency] private readonly ISharedPlayerManager _playerManager = default!; // Reserve edit: Fix warnings
    // [Dependency] private readonly IGameTiming _gameTiming = default!; // Reserve edit: Fix warnings

    public ActionsTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public override bool UpdateState()
    {
        UpdateButtonsLayout();
        return true;
    }

    private void UpdateButtonsLayout()
    {
    }

    protected override void Resized()
    {
        UpdateButtonsLayout();
    }
}
