# SPDX-License-Identifier: AGPL-3.0-or-later

# region Dynamic, Clothing

- type: latheRecipe
  id: ClothingOuterApronBotanistAdvanced
  result: ClothingOuterApronBotanistAdvanced
  completetime: 2
  materials:
    Cloth: 500
    Durathread: 100
    Steel: 50

- type: latheRecipe
  parent: ClothingOuterApronBotanistAdvanced
  id: ClothingOuterApronChemist
  result: ClothingOuterApronChemist

- type: latheRecipe
  id: ClothingHandsGlovesBotanistAdvanced
  result: ClothingHandsGlovesBotanistAdvanced
  completetime: 2
  materials:
    Cloth: 200
    Durathread: 100
    Plastic: 50
    Steel: 50

- type: latheRecipe
  parent: ClothingHandsGlovesBotanistAdvanced
  id: ClothingHandsGlovesChemistAdvanced
  result: ClothingHandsGlovesChemistAdvanced

- type: latheRecipe
  id: ClothingHandsGlovesMitts
  result: ClothingHandsGlovesMitts
  completetime: 2
  materials:
    Cloth: 250

- type: latheRecipe
  parent: ClothingHandsGlovesMitts
  id: ClothingHandsGlovesMittsChemist
  result: ClothingHandsGlovesMittsChemist

- type: latheRecipe
  id: ClothingMaskBreathBotanistAdvanced
  result: ClothingMaskBreathBotanistAdvanced
  completetime: 2
  materials:
    Glass: 50
    Plastic: 100
    Cloth: 100

- type: latheRecipe
  parent: ClothingMaskBreathBotanistAdvanced
  id: ClothingMaskBreathChemist
  result: ClothingMaskBreathChemist

- type: latheRecipe
  id: ClothingEyesGogglesBotanistAdvanced
  result: ClothingEyesGogglesBotanistAdvanced
  completetime: 2
  materials:
    Glass: 100
    Plastic: 100
    Cloth: 100

- type: latheRecipe
  id: ClothingHeadHatChefBluespace
  result: ClothingHeadHatChefBluespace
  completetime: 3
  materials:
    Cloth: 200
    BSCrystal: 20

# endregion

# region Dynamic, Tools

- type: latheRecipePack
  id: PlantAnalyzer
  recipes:
  - PlantAnalyzer

- type: latheRecipe
  id: BluespaceBucket
  result: BluespaceBucket
  completetime: 3
  materials:
    Steel: 100
    Plastic: 500
    Plasma: 150
    BSCrystal: 50

- type: latheRecipe
  id: TrashBagOfHolding
  result: TrashBagOfHolding
  completetime: 3
  materials:
    Plastic: 100
    Plasma: 100
    BSCrystal: 40

- type: latheRecipe
  id: WateringCan
  result: WateringCan
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: BluespaceWateringCanExperimental
  result: BluespaceWateringCanExperimental
  completetime: 5
  materials:
    Steel: 500
    Plastic: 500
    Plasma: 250
    BSCrystal: 50

- type: latheRecipe
  id: WateringCanExperimental
  result: WateringCanExperimental
  completetime: 4
  materials:
    Steel: 500
    Plastic: 500
    Plasma: 250

- type: latheRecipe
  id: DrinkShakerAdvanced
  result: DrinkShakerAdvanced
  completetime: 2
  materials:
    Steel: 200
    Plastic: 500
    Glass: 50

- type: latheRecipe
  parent: DrinkShakerAdvanced
  id: DrinkKettleAdvanced
  result: DrinkKettleAdvanced

- type: latheRecipe
  id: BluespaceDrinkShakerAdvanced
  result: BluespaceDrinkShakerAdvanced
  completetime: 3
  materials:
    Steel: 200
    Plastic: 500
    Glass: 50
    Plasma: 50
    BSCrystal: 50

- type: latheRecipe
  parent: BluespaceDrinkShakerAdvanced
  id: BluespaceDrinkKettleAdvanced
  result: BluespaceDrinkKettleAdvanced

# endregion
