# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Vampire
  name: roles-antag-vampire-name
  antagonist: true
  setPreference: true
  objective: roles-antag-vampire-description
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3h
  category: Solo
  icon:
    sprite: _Reserve/Vampire/actions_vampire.rsi
    state: fangs_extended
