// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Reserve.Inventory.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Reserve.Inventory.UI;

[GenerateTypedNameReferences]
public sealed partial class AntagSelectionWindow : DefaultWindow
{
    public event Action<string>? OnSelectRule;

    public AntagSelectionWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(AntagSelectionEuiState state)
    {
        RulesContainer.DisposeAllChildren();

        if (state.Rules.Count == 0)
        {
            RulesContainer.AddChild(new Label
            {
                Text = Loc.GetString("reserve-antag-selection-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 8, 0, 0),
            });
            return;
        }

        foreach (var rule in state.Rules)
        {
            var button = new Button
            {
                Text = rule.DisplayName,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 4),
            };
            var ruleId = rule.RuleId;
            button.OnPressed += _ => OnSelectRule?.Invoke(ruleId);
            RulesContainer.AddChild(button);
        }
    }
}
