// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared._Reserve.Inventory.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._Reserve.Inventory.UI;

[GenerateTypedNameReferences]
public sealed partial class CosmeticSelectionWindow : DefaultWindow
{
    public event Action<string>? OnSelectItem;

    private readonly IPrototypeManager _proto;
    private readonly SpriteSystem _spriteSystem;

    private List<(string ProtoId, EntityPrototype Prototype)> _allItems = new();

    public CosmeticSelectionWindow()
    {
        RobustXamlLoader.Load(this);
        _proto = IoCManager.Resolve<IPrototypeManager>();
        _spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
        SearchBar.OnTextChanged += args => FilterItems(args.Text);
    }

    public void Populate(CosmeticSelectionEuiState state)
    {
        _allItems = new List<(string, EntityPrototype)>();
        foreach (var protoId in state.ProtoIds)
        {
            if (_proto.TryIndex<EntityPrototype>(protoId, out var prototype))
                _allItems.Add((protoId, prototype));
        }
        FilterItems(SearchBar.Text);
    }

    private void FilterItems(string query)
    {
        ItemsGrid.DisposeAllChildren();

        foreach (var (protoId, prototype) in _allItems)
        {
            if (!string.IsNullOrEmpty(query) &&
                !prototype.Name.Contains(query, StringComparison.OrdinalIgnoreCase))
                continue;

            var protoIdCopy = protoId;
            var texture = _spriteSystem.Frame0(prototype);

            var button = new TextureButton
            {
                TextureNormal = texture,
                ToolTip = prototype.Name,
                Scale = new Vector2(2, 2),
                HorizontalAlignment = HAlignment.Center,
            };
            button.OnPressed += _ => OnSelectItem?.Invoke(protoIdCopy);

            var iconBox = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2b2b2b") },
                HorizontalAlignment = HAlignment.Center,
            };
            iconBox.AddChild(button);

            var label = new Label
            {
                Text = prototype.Name,
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = Color.FromHex("#cccccc"),
                Margin = new Thickness(0, 2, 0, 0),
            };
            label.SetOnlyStyleClass("LabelSmall");

            var card = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(4),
            };
            card.AddChild(iconBox);
            card.AddChild(label);

            ItemsGrid.AddChild(card);
        }
    }
}
