// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Shared._Reserve.Inventory.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._Reserve.Inventory.UI;

[GenerateTypedNameReferences]
public sealed partial class InventoryWindow : DefaultWindow
{
    public event Action<string>? OnUseItem;

    public InventoryWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(InventoryEuiState state)
    {
        ItemsContainer.DisposeAllChildren();

        if (state.IsLoading)
        {
            StatusLabel.Visible = true;
            StatusLabel.Text = Loc.GetString("reserve-inventory-loading");
            return;
        }

        if (state.ErrorMessage != null)
        {
            StatusLabel.Visible = true;
            StatusLabel.Text = state.ErrorMessage;
            return;
        }

        var items = state.Items;
        if (items == null || items.Count == 0)
        {
            StatusLabel.Visible = true;
            StatusLabel.Text = Loc.GetString("reserve-inventory-empty");
            return;
        }

        StatusLabel.Visible = false;

        foreach (var item in items)
        {
            var card = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(4),
            };

            var iconPanel = new PanelContainer
            {
                MinSize = new Vector2(64, 64),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 0, 0, 4),
            };
            if (item.IconPath != null)
            {
                var resources = IoCManager.Resolve<IResourceCache>();
                if (resources.TryGetResource<TextureResource>(item.IconPath, out var texture))
                {
                    iconPanel.AddChild(new TextureRect
                    {
                        Texture = texture.Texture,
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        HorizontalExpand = true,
                        VerticalExpand = true,
                    });
                }
            }
            card.AddChild(iconPanel);

            var nameLabel = new Label
            {
                Text = item.ItemName,
                HorizontalAlignment = HAlignment.Center,
                HorizontalExpand = true,
            };
            card.AddChild(nameLabel);

            var useButton = new Button
            {
                Text = Loc.GetString("reserve-inventory-use-button"),
                HorizontalExpand = true,
                Margin = new Thickness(0, 4, 0, 0),
            };
            var itemId = item.ItemId;
            useButton.OnPressed += _ => OnUseItem?.Invoke(itemId);
            card.AddChild(useButton);

            ItemsContainer.AddChild(card);
        }
    }

}
