# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  goobcoins: 10 #Goob content
  weight: 3  # Reserve edit: Fix Service Department job order
  access:
  - Service
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: ClothingHandsGlovesBoxingRigged
  alternateTitles: # Reserve - alternate titles
  - BoxerFitnessInstructor
  - BoxerYogaInstructor
  - BoxerLifeCoach
  - BoxerPersonalTrainer
  - BoxerHeel

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BoxerChameleonOutfit
  job: Boxer
  equipment:
    head: ClothingHeadHatBlacksoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorGray
    jumpsuit: UniformShortsRedWithTop
    neck: ClothingNeckScarfStripedRed

- type: jobAlternateTitle
  id: BoxerFitnessInstructor
  name: job-name-alt-boxer-1

- type: jobAlternateTitle
  id: BoxerYogaInstructor
  name: job-name-alt-boxer-2

- type: jobAlternateTitle
  id: BoxerLifeCoach
  name: job-name-alt-boxer-3

- type: jobAlternateTitle
  id: BoxerPersonalTrainer
  name: job-name-alt-boxer-4

- type: jobAlternateTitle
  id: BoxerHeel
  name: job-name-alt-boxer-5
