// SPDX-FileCopyrightText: 2025 Goob Station Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Patron;

[GenerateTypedNameReferences]
public sealed partial class PatronSupportWindow : FancyWindow
{
    public PatronSupportWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
