// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // Reserve-LenaApi
using Content.Shared._Reserve.LenaApi; // Reserve-LenaApi

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!; // Reserve-LenaApi
    [Dependency] private readonly IUriOpener _uriOpener = default!; // Reserve-LenaApi

    private readonly string _shopUri; // Reserve-LenaApi

    public Button CharacterSetupButton => CharacterSetup;

    private EntityUid? _previewDummy;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Reserve-LenaApi-start
        _shopUri = _cfg.GetCVar(LenaApiCVars.ShopUri);
        CurrencyWeb.OnPressed += _ => _uriOpener.OpenUri(_shopUri);
        _cfg.OnValueChanged(LenaApiCVars.ApiIntegration, OnApiIntegrationChanged, true);
        // Reserve-LenaApi-end

    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    public void SetSummaryText(string value)
    {
        Summary.Text = value;
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        ViewBox.RemoveAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            Scale = new Vector2(4f, 4f),
            MaxSize = new Vector2(112, 112),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    private void OnApiIntegrationChanged(bool enabled) // Reserve-LenaApi
    {
        Currency.Visible = !enabled;
        CurrencyWeb.Visible = enabled;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = null;

        _cfg.UnsubValueChanged(LenaApiCVars.ApiIntegration, OnApiIntegrationChanged); // Reserve-LenaApi
    }
}
