# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 0.5h
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  guides: # goobstation
  - Bartender
  - Drinks
  goobcoins: 10 #Goob content
  weight: 7  # Reserve edit: Fix Service Department job order
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics
  alternateTitles: # Reserve - alternate titles
  - BartenderMixologist
  - BartenderBarista
  - BartenderHydrationEquipmentOperator

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BartenderChameleonOutfit
  job: Bartender
  equipment:
    head: ClothingHeadHatTophat
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedBlack
    outerClothing: ClothingOuterArmorBasicSlim
    gloves: ClothingHandsGlovesColorBlack

- type: jobAlternateTitle
  id: BartenderMixologist
  name: job-name-alt-bartender-1

- type: jobAlternateTitle
  id: BartenderHydrationEquipmentOperator
  name: job-name-alt-bartender-2

- type: jobAlternateTitle
  id: BartenderBarista
  name: job-name-alt-bartender-3
