// SPDX-License-Identifier: MIT

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._Reserve.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class VendingMachineKeypadKey : LayoutContainer
{
    private const float NativeSize = 32f;
    private const float DisplayScale = 1.5f;
    private const float PressedDarken = 0.7f;

    public event Action? OnKeyPressed;

    [Dependency] private IResourceCache _resourceCache = null!;

    private Color _baseColor = Color.White;
    private Color _hoverColor = new Color(1.2f, 1.2f, 1.2f);
    private Color _pressedColor = new Color(PressedDarken, PressedDarken, PressedDarken);

    public VendingMachineKeypadKey(string key)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        KeyLabel.Text = key;
        KeyLabel.FontColorOverride = new Color(0x80, 0x7b, 0x7a);
        KeyLabel.FontOverride = new VectorFont(_resourceCache.GetResource<FontResource>("/Fonts/Sysfont/Sysfont-Regular.otf"), 14);

        var displaySize = NativeSize * DisplayScale;
        SetSize = new Vector2(displaySize, displaySize);

        KeySprite.SetSize = new Vector2(displaySize, displaySize);
        LayoutContainer.SetPosition(KeySprite, Vector2.Zero);

        KeyLabel.Measure(Vector2Helpers.Infinity);
        var labelSize = KeyLabel.DesiredSize;
        const float perspectiveLift = 4f;
        var labelPos = new Vector2(
            (displaySize - labelSize.X) / 2f,
            (displaySize - labelSize.Y) / 2f - perspectiveLift);
        LayoutContainer.SetPosition(KeyLabel, labelPos);

        MouseFilter = MouseFilterMode.Stop;
        OnKeyBindDown += OnPress;
        OnKeyBindUp += OnRelease;

        OnMouseEntered += _ => KeySprite.Modulate = _hoverColor;
        OnMouseExited += _ => KeySprite.Modulate = _baseColor;
    }

    public void SetTint(Color baseColor, Color hoverColor, Color fontColor)
    {
        _baseColor = baseColor;
        _hoverColor = hoverColor;

        _pressedColor = new Color(baseColor.R * 0.7f, baseColor.G * 0.7f, baseColor.B * 0.7f);

        KeySprite.Modulate = _baseColor;
        KeyLabel.FontColorOverride = fontColor;
    }

    private void OnPress(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        KeySprite.Modulate = _pressedColor;
        args.Handle();
    }

    private void OnRelease(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        KeySprite.Modulate = _baseColor;
        args.Handle();

        OnKeyPressed?.Invoke();
    }
}
