# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 2.5h
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  guides: [ Science ] # goobstation
  goobcoins: 20 #Goob content
  weight: 9  # Reserve edit: Fix Assistant job order
  access:
  - Research
  - Maintenance
  alternateTitles: # Reserve - alternate titles
  - ScientistXenoarchaeologist
  - ScientistAnomalyResearcher
  - ScientistHardwareTechnician

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ScientistChameleonOutfit
  job: Scientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex

- type: jobAlternateTitle
  id: ScientistXenoarchaeologist
  name: job-name-alt-scientist-1

- type: jobAlternateTitle
  id: ScientistAnomalyResearcher
  name: job-name-alt-scientist-2

- type: jobAlternateTitle
  id: ScientistHardwareTechnician
  name: job-name-alt-scientist-3
