# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  setPreference: false # Reserve edit
  objective: roles-antag-dragon-objective
  # Reserve - antag UI
  category: Solo
  icon:
    sprite: Mobs/Aliens/Carps/dragon.rsi
    state: dead
