// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Tools;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideFoodIngredientEmbed : PanelContainer, IDocumentTag, ISearchableControl, IGuidebookEntryAnchor
{
    private static readonly ProtoId<ToolQualityPrototype> SlicingTool = "Slicing";
    private static readonly ProtoId<ToolQualityPrototype> RollingTool = "Rolling";

    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;

    private FoodGuideDataSystem _foodGuideData = default!;

    public IPrototype? AnchorPrototype { get; private set; }

    public GuideFoodIngredientEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _foodGuideData = _entitySystemManager.GetEntitySystem<FoodGuideDataSystem>();
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideFoodIngredientEmbed(EntityPrototype entity, string group) : this()
    {
        GenerateControl(entity, group);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Group", out var group))
            return false;

        if (!args.TryGetValue("Entity", out var id))
            return false;

        if (!_prototype.TryIndex<EntityPrototype>(id, out var entity))
            return false;

        GenerateControl(entity, group);
        control = this;
        return true;
    }

    private void GenerateControl(EntityPrototype entity, string group)
    {
        if (!_foodGuideData.HasObtainSource(entity.ID))
        {
            Visible = false;
            return;
        }

        AnchorPrototype = entity;

        IconContainer.AddChild(new GuideEntityEmbed(entity.ID, false, false, registerAsGuideAnchor: false));
        IngredientName.SetMarkup(entity.Name);

        if (string.IsNullOrWhiteSpace(entity.Description))
            DescriptionContainer.Visible = false;
        else
            IngredientDescription.SetMarkup(entity.Description);

        foreach (var source in _foodGuideData.GetNonPlantSources(entity.ID))
        {
            switch (source.Kind)
            {
                case FoodEntitySourceKind.MixingReaction when source.Reaction != null && source.Group == group:
                    SourcesContainer.AddChild(
                        new GuideReagentReaction(source.Reaction, entity.ID, _prototype, _entitySystemManager));
                    break;
                case FoodEntitySourceKind.SliceFrom when source.SourceEntity != null && source.Group == group:
                    SourcesContainer.AddChild(new GuideFoodEntitySourceReaction(
                        source.SourceEntity.Value,
                        entity.ID,
                        SlicingTool,
                        _prototype,
                        _entitySystemManager));
                    break;
                case FoodEntitySourceKind.RollFrom when source.SourceEntity != null && source.Group == group:
                    SourcesContainer.AddChild(new GuideFoodEntitySourceReaction(
                        source.SourceEntity.Value,
                        entity.ID,
                        RollingTool,
                        _prototype,
                        _entitySystemManager));
                    break;
            }
        }

        if (SourcesContainer.ChildCount == 0)
            SourcesContainer.Visible = false;
    }
}
