// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Tools;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideFoodEntitySourceReaction : BoxContainer, ISearchableControl
{
    public GuideFoodEntitySourceReaction(
        EntProtoId sourceEntity,
        EntProtoId resultEntity,
        ProtoId<ToolQualityPrototype> toolQuality,
        IPrototypeManager protoMan,
        IEntitySystemManager sysMan) : this()
    {
        var spriteSystem = sysMan.GetEntitySystem<SpriteSystem>();
        var quality = protoMan.Index(toolQuality);

        AddEntity(ReactantsContainer, sourceEntity, link: true, protoMan, spriteSystem);
        AddEntity(ProductsContainer, resultEntity, link: false, protoMan, spriteSystem);

        ActionTexture.Texture = quality.Icon is { } icon ? spriteSystem.Frame0(icon) : null;
        ActionLabel.SetMarkup(Loc.GetString("construction-presenter-tool-step", ("tool", quality.ToolName)));

        ReactantsContainer.Visible = true;
        ProductsContainer.Visible = true;
    }

    public GuideFoodEntitySourceReaction()
    {
        RobustXamlLoader.Load(this);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private static void AddEntity(
        Container container,
        EntProtoId entityId,
        bool link,
        IPrototypeManager protoMan,
        SpriteSystem spriteSystem)
    {
        var prototype = protoMan.Index<EntityPrototype>(entityId);
        var icon = spriteSystem.GetPrototypeIcon(prototype).GetFrame(RsiDirection.South, 0);

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            Children =
            {
                new TextureRect { Texture = icon }
            }
        };

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("guidebook-food-entity-craft-result", ("name", prototype.Name)));
        msg.Pop();

        if (link)
        {
            var label = new GuidebookCrossRefLabel();
            label.SetMessage(msg);
            label.TargetPrototype = prototype;
            row.AddChild(label);
        }
        else
        {
            var label = new RichTextLabel();
            label.SetMessage(msg);
            row.AddChild(label);
        }

        container.AddChild(row);
    }
}
