// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook;
using Content.Client.Guidebook.Richtext;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideFoodIngredientGroupEmbed : BoxContainer, IDocumentTag
{
    // [Dependency] private readonly IPrototypeManager _prototype = default!; // Reserve edit: Fix warnings
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;

    public GuideFoodIngredientGroupEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    public GuideFoodIngredientGroupEmbed(string group) : this()
    {
        Populate(group);
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Group", out var group))
        {
            Logger.Error("Recipe group embed tag is missing group argument");
            return false;
        }

        Populate(group);

        control = this;
        return true;
    }

    private void Populate(string group)
    {
        GroupContainer.RemoveAllChildren();

        var foodGuide = _entitySystemManager.GetEntitySystem<FoodGuideDataSystem>();
        var addedRecipes = new HashSet<string>();

        foreach (var entity in foodGuide.GetGuideIngredients())
        {
            foreach (var recipe in foodGuide.GetMicrowaveRecipes(entity.ID))
            {
                if (recipe.Group != group)
                    continue;

                if (addedRecipes.Add(recipe.ID))
                    GroupContainer.AddChild(new GuideMicrowaveEmbed(recipe));
            }

            var hasNonMicrowaveSource = false;
            foreach (var source in foodGuide.GetNonPlantSources(entity.ID))
            {
                if (source.Kind is FoodEntitySourceKind.MixingReaction
                    or FoodEntitySourceKind.SliceFrom
                    or FoodEntitySourceKind.RollFrom
                    && source.Group == group)
                {
                    hasNonMicrowaveSource = true;
                    break;
                }
            }

            if (hasNonMicrowaveSource)
                GroupContainer.AddChild(new GuideFoodIngredientEmbed(entity, group));
        }
    }
}
