// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Chemistry.Components;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Goobstation.Maths.FixedPoint;
using Content.Shared.Localizations;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideReagentReaction : BoxContainer, ISearchableControl
{
    private static readonly ProtoId<MixingCategoryPrototype> DefaultMixingCategory = "DummyMix";

    private readonly IPrototypeManager _protoMan;

    public GuideReagentReaction(IPrototypeManager protoMan)
    {
        RobustXamlLoader.Load(this);
        _protoMan = protoMan;
    }

    public GuideReagentReaction(ReactionPrototype prototype, IPrototypeManager protoMan, IEntitySystemManager sysMan) : this(protoMan)
    {
        // Reserve edit start: guide-book #320
        Container reactantsContainer = ReactantsContainer;
        SetReagents(prototype.Reactants, ref reactantsContainer, protoMan);
        Container productsContainer = ProductsContainer;
        var products = new Dictionary<string, FixedPoint2>(prototype.Products.ToDictionary(p => p.Key.Id, p => p.Value));
        foreach (var (reagent, reactantProto) in prototype.Reactants)
        {
            if (reactantProto.Catalyst)
                products.Add(reagent, reactantProto.Amount);
        }
        SetReagents(products, ref productsContainer, protoMan, addLinks: false);
        // Reserve edit end: guide-book #320

        var mixingCategories = new List<MixingCategoryPrototype>();
        if (prototype.MixingCategories != null)
        {
            foreach (var category in prototype.MixingCategories)
            {
                mixingCategories.Add(protoMan.Index(category));
            }
        }
        else
        {
            mixingCategories.Add(protoMan.Index(DefaultMixingCategory));
        }
        SetMixingCategory(mixingCategories, prototype, sysMan);
    }

    // Reserve edit start: guide-book #320
    public GuideReagentReaction(
        ReactionPrototype prototype,
        EntProtoId outputEntity,
        IPrototypeManager protoMan,
        IEntitySystemManager sysMan) : this(protoMan)
    {
        Container reactantsContainer = ReactantsContainer;
        SetReagents(prototype.Reactants, ref reactantsContainer, protoMan);

        var output = protoMan.Index<EntityPrototype>(outputEntity);
        var icon = sysMan.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(output).GetFrame(RsiDirection.South, 0);
        var entContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            Children =
            {
                new TextureRect { Texture = icon }
            }
        };
        var nameLabel = new RichTextLabel();
        nameLabel.SetMarkup(Loc.GetString("guidebook-food-entity-craft-result", ("name", output.Name)));
        entContainer.AddChild(nameLabel);
        ProductsContainer.AddChild(entContainer);
        ProductsContainer.Visible = true;

        var mixingCategories = new List<MixingCategoryPrototype>();
        if (prototype.MixingCategories != null)
        {
            foreach (var category in prototype.MixingCategories)
                mixingCategories.Add(protoMan.Index(category));
        }
        else
        {
            mixingCategories.Add(protoMan.Index(DefaultMixingCategory));
        }

        SetMixingCategory(mixingCategories, prototype, sysMan);
    }
    // Reserve edit end: guide-book #320

    public GuideReagentReaction(EntityPrototype prototype,
        Solution solution,
        IReadOnlyList<ProtoId<MixingCategoryPrototype>> categories,
        IPrototypeManager protoMan,
        IEntitySystemManager sysMan) : this(protoMan)
    {
        var icon = sysMan.GetEntitySystem<SpriteSystem>().GetPrototypeIcon(prototype).GetFrame(RsiDirection.South, 0);
        var entContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            Children =
            {
                new TextureRect
                {
                    Texture = icon
                }
            }
        };
        var nameLabel = new RichTextLabel();
        nameLabel.SetMarkup(Loc.GetString("guidebook-reagent-sources-ent-wrapper", ("name", prototype.Name)));
        entContainer.AddChild(nameLabel);
        ReactantsContainer.AddChild(entContainer);

        // Reserve edit start: guide-book #320
        Container productsContainer = ProductsContainer;
        SetReagents(solution.Contents, ref productsContainer, protoMan, addLinks: false);
        // Reserve edit end: guide-book #320
        SetMixingCategory(categories, null, sysMan);
    }

    public GuideReagentReaction(GasPrototype prototype,
        IReadOnlyList<ProtoId<MixingCategoryPrototype>> categories,
        IPrototypeManager protoMan,
        IEntitySystemManager sysMan) : this(protoMan)
    {
        // Reserve edit start: guide-book #320
        var label = new RichTextLabel();
        label.SetMarkup(Loc.GetString("guidebook-reagent-sources-gas-wrapper",
            ("name", Loc.GetString(prototype.Name).ToLower())));

        ReactantsContainer.Visible = true;
        ReactantsContainer.AddChild(label);

        if (prototype.Reagent != null)
        {
            var quantity = new Dictionary<string, FixedPoint2>
            {
                { prototype.Reagent, FixedPoint2.New(0.21f) }
            };
            Container productsContainer = ProductsContainer;
            SetReagents(quantity, ref productsContainer, protoMan, addLinks: false);
        }
        // Reserve edit end: guide-book #320
        SetMixingCategory(categories, null, sysMan);
    }

    // Reserve edit start: guide-book #320
    private void SetReagents(List<ReagentQuantity> reagents, ref Container container, IPrototypeManager protoMan, bool addLinks = true)
    {
        var amounts = new Dictionary<string, FixedPoint2>();
        foreach (var (reagent, quantity) in reagents)
        {
            amounts.Add(reagent.Prototype, quantity);
        }
        SetReagents(amounts, ref container, protoMan, addLinks);
    }

    private void SetReagents(
        Dictionary<ProtoId<ReagentPrototype>, ReactantPrototype> reactants,
        ref Container container,
        IPrototypeManager protoMan,
        bool addLinks = true)
    {
        var amounts = new Dictionary<string, FixedPoint2>();
        foreach (var (reagent, reactantPrototype) in reactants)
        {
            amounts.Add(reagent, reactantPrototype.Amount);
        }
        SetReagents(amounts, ref container, protoMan, addLinks);
    }

    [PublicAPI]
    private void SetReagents(
        Dictionary<ProtoId<MixingCategoryPrototype>, ReactantPrototype> reactants,
        ref Container container,
        IPrototypeManager protoMan,
        bool addLinks = true)
    {
        var amounts = new Dictionary<string, FixedPoint2>();
        foreach (var (reagent, reactantPrototype) in reactants)
        {
            amounts.Add(reagent, reactantPrototype.Amount);
        }
        SetReagents(amounts, ref container, protoMan, addLinks);
    }

    private void SetReagents(Dictionary<string, FixedPoint2> reagents, ref Container container, IPrototypeManager protoMan, bool addLinks = true)
    {
        foreach (var (product, amount) in reagents.OrderByDescending(p => p.Value))
        {
            var productProto = protoMan.Index<ReagentPrototype>(product);
            var msg = new FormattedMessage();
            msg.AddMarkupOrThrow(Loc.GetString("guidebook-reagent-recipes-reagent-display",
                ("reagent", productProto.LocalizedName), ("ratio", amount)));

            if (addLinks)
            {
                var link = new GuidebookCrossRefLabel();
                link.TargetPrototype = productProto;
                link.SetMessage(msg);
                container.AddChild(link);
            }
            else
            {
                var label = new RichTextLabel();
                label.SetMessage(msg);
                container.AddChild(label);
            }
        }
        container.Visible = true;
    }
    // Reserve edit end: guide-book #320

    private void SetMixingCategory(IReadOnlyList<ProtoId<MixingCategoryPrototype>> mixingCategories, ReactionPrototype? prototype, IEntitySystemManager sysMan)
    {
        var foo = new List<MixingCategoryPrototype>();
        foreach (var cat in mixingCategories)
        {
            foo.Add(_protoMan.Index(cat));
        }
        SetMixingCategory(foo, prototype, sysMan);
    }

    private void SetMixingCategory(IReadOnlyList<MixingCategoryPrototype> mixingCategories, ReactionPrototype? prototype, IEntitySystemManager sysMan)
    {
        if (mixingCategories.Count == 0)
            return;

        // only use the first one for the icon.
        if (mixingCategories.First() is { } primaryCategory)
        {
            MixTexture.Texture = sysMan.GetEntitySystem<SpriteSystem>().Frame0(primaryCategory.Icon);
        }

        var mixingVerb = ContentLocalizationManager.FormatList(mixingCategories
            .Select(p => Loc.GetString(p.VerbText)).ToList());

        var minTemp = prototype?.MinimumTemperature ?? 0;
        var maxTemp = prototype?.MaximumTemperature ?? float.PositiveInfinity;
        var text = Loc.GetString("guidebook-reagent-recipes-mix-info",
            ("verb", mixingVerb),
            ("minTemp", minTemp),
            ("maxTemp", maxTemp),
            ("hasMax", !float.IsPositiveInfinity(maxTemp)));

        MixLabel.SetMarkup(text);
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }
}
