// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client.UserInterface.Systems.Info;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;

namespace Content.Client.Guidebook.Controls;

[GenerateTypedNameReferences]
// Reserve edit start: guide-book #320
public sealed partial class GuidebookWindow : FancyWindow, ILinkClickHandler, IGuidebookCrossReferenceNavigator
{
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IResourceManager _resourceManager = default!;
    [Dependency] private readonly GuidebookLocalizationManager _localization = default!;

    private Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> _entries = new();
    private readonly GuidebookCrossReferenceIndex _crossReferences = new();
    private GuideEntry? _currentGuideEntry;
    private List<ProtoId<GuideEntryPrototype>>? _treeRootEntries;
    private ProtoId<GuideEntryPrototype>? _treeForceRoot;
    private bool _suppressSelectionReload;
    // Reserve edit end: guide-book #320

    private readonly ISawmill _sawmill;

    public ProtoId<GuideEntryPrototype> LastEntry;

    public GuidebookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = Logger.GetSawmill("Guidebook");

        Tree.OnSelectedItemChanged += OnSelectionChanged;

        SearchBar.OnTextChanged += _ =>
        {
            HandleFilter();
        };

        // Reserve edit start: guide-book #320
        HomeButton.OnPressed += _ =>
        {
            if (_currentGuideEntry != null)
                ShowGuide(_currentGuideEntry, resetState: true); // Reserve edit: guide-book #323
        };
        // Reserve edit end: guide-book #320
    }

    public void HandleClick(string link)
    {
        if (!_entries.TryGetValue(link, out var entry))
            return;

        if (Tree.TryGetIndexFromMetadata(entry, out var index))
        {
            Tree.ExpandParentEntries(index.Value);
            Tree.SetSelectedIndex(index);
        }
        else
            ShowGuide(entry);
    }

    // Reserve edit start: guide-book #320
    public void NavigateToCrossReferenceTarget(IGuidebookCrossReference reference)
    {
        if (reference.TargetPrototype is not { } target)
            return;

        _crossReferences.TryRevealAndScroll(target, Scroll, UserInterfaceManager);
    }
    // Reserve edit end: guide-book #320

    private void OnSelectionChanged(TreeItem? item)
    {
        if (item != null && item.Metadata is GuideEntry entry)
        {
            // Reserve edit start: guide-book #320, #323
            if (_suppressSelectionReload
                || (_currentGuideEntry?.Id == entry.Id && EntryContainer.ChildCount > 0))
            {
                ReturnContainer.Visible = entry.RuleEntry;
                return;
            }

            SaveCurrentPageState();
            _currentGuideEntry = entry;
            ShowGuide(entry);
            // Reserve edit end: guide-book #320, #323

            ReturnContainer.Visible = entry.RuleEntry; // Reserve edit: guide-book #323
        }
        else
            ClearSelectedGuide();
    }

    public void ClearSelectedGuide()
    {
        Placeholder.Visible = true;
        EntryContainer.Visible = false;
        SearchContainer.Visible = false;
        EntryContainer.RemoveAllChildren();
        // Reserve edit start: guide-book #320
        _crossReferences.Clear();
        _currentGuideEntry = null;
        // Reserve edit end: guide-book #320
    }

    // Reserve edit start: guide-book #320, #323
    public void SaveCurrentPageState()
    {
        if (_currentGuideEntry == null)
            return;

        GuidebookPageStateStorage.States[_currentGuideEntry.Id] = new GuidebookPageState(
            Scroll.GetScrollValue(),
            SearchBar.Text ?? string.Empty,
            CollectExpandedCollapsibles(EntryContainer),
            CollectRevealedEntryAnchors(EntryContainer, SearchBar.Text ?? string.Empty)); // Reserve edit: guide-book #323
    }

    private void ShowGuide(GuideEntry entry, bool resetState = false)
    {
        var pageState = resetState
            ? GuidebookPageStateStorage.Empty
            : GuidebookPageStateStorage.States.GetValueOrDefault(entry.Id, GuidebookPageStateStorage.Empty);
        Placeholder.Visible = false;
        EntryContainer.Visible = true;
        EntryContainer.RemoveAllChildren();
        // using var file = _resourceManager.ContentFileReadText(entry.Text); // Reserve localized guidebook begin
        // Get localized path
        var textPath = entry.GetLocalizedTextPath(_localization.GetCurrentCultureName());

        if (textPath == default)
        {
            _sawmill.Error($"Guide entry {entry.Id} has no valid text path!");
            return;
        }

        using var file = _resourceManager.ContentFileReadText(textPath);
        // Reserve localized guidebook end

        SearchContainer.Visible = entry.FilterEnabled;

        if (!_parsingMan.TryAddMarkup(EntryContainer, file.ReadToEnd()))
        {
            // The guidebook will automatically display the in-guidebook error if it fails

            _sawmill.Error($"Failed to parse contents of guide document {entry.Id}.");
        }

        LastEntry = entry.Id;

        // Reserve edit: guide-book #320, #323
        _crossReferences.BuildFromPage(EntryContainer);
        ApplyPageState(pageState);
    }

    // Reserve edit: guide-book #323
    private void ApplyPageState(GuidebookPageState state)
    {
        SearchBar.SetText(state.Search, invokeEvent: false);

        if (!string.IsNullOrEmpty(state.Search))
            HandleFilter();

        UserInterfaceManager.DeferAction(() =>
        {
            ApplyRevealedEntryAnchors(EntryContainer, state.RevealedEntryAnchors);
            ApplyCollapsibleStates(EntryContainer, state.ExpandedCollapsibles);
            Scroll.SetScrollValue(state.Scroll);
        });
    }

    private static HashSet<string> CollectRevealedEntryAnchors(Control root, string search)
    {
        var revealed = new HashSet<string>();

        if (string.IsNullOrWhiteSpace(search))
            return revealed;

        var query = search.Trim();
        foreach (var anchor in EnumerateEntryAnchors(root))
        {
            if (anchor is not Control { Visible: true } control)
                continue;

            if (control is not ISearchableControl searchable)
                continue;

            if (searchable.CheckMatchesSearch(query))
                continue;

            if (anchor.AnchorPrototype is { } proto)
                revealed.Add(proto.ID);
        }

        return revealed;
    }

    private static void ApplyRevealedEntryAnchors(Control root, HashSet<string> revealed)
    {
        if (revealed.Count == 0)
            return;

        foreach (var anchor in EnumerateEntryAnchors(root))
        {
            if (anchor.AnchorPrototype is not { } proto)
                continue;

            if (!revealed.Contains(proto.ID))
                continue;

            if (anchor is Control control)
                control.Visible = true;
        }
    }

    private static IEnumerable<IGuidebookEntryAnchor> EnumerateEntryAnchors(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is IGuidebookEntryAnchor anchor)
                yield return anchor;

            foreach (var nested in EnumerateEntryAnchors(child))
                yield return nested;
        }
    }

    private static HashSet<string> CollectExpandedCollapsibles(Control root)
    {
        var expanded = new HashSet<string>();

        foreach (var collapsible in EnumerateCollapsibles(root))
        {
            if (!IsCollapsibleExpanded(collapsible))
                continue;

            if (GetCollapsibleKey(collapsible) is { } key)
                expanded.Add(key);
        }

        return expanded;
    }

    private static void ApplyCollapsibleStates(Control root, HashSet<string> expanded)
    {
        foreach (var collapsible in EnumerateCollapsibles(root))
        {
            if (GetCollapsibleKey(collapsible) is not { } key)
                continue;

            collapsible.BodyVisible = expanded.Contains(key);
        }
    }

    private static IEnumerable<Collapsible> EnumerateCollapsibles(Control root)
    {
        foreach (var child in root.Children)
        {
            if (child is Collapsible collapsible)
                yield return collapsible;

            foreach (var nested in EnumerateCollapsibles(child))
                yield return nested;
        }
    }

    private static bool IsCollapsibleExpanded(Collapsible collapsible)
    {
        if (collapsible.BodyVisible)
            return true;

        var heading = GetCollapsibleHeading(collapsible);
        return heading is { Pressed: true };
    }

    private static CollapsibleHeading? GetCollapsibleHeading(Collapsible collapsible)
    {
        if (collapsible.Heading is CollapsibleHeading heading)
            return heading;

        foreach (var child in collapsible.Children)
        {
            if (child is CollapsibleHeading collapsibleHeading)
                return collapsibleHeading;
        }

        return null;
    }

    private static string? GetCollapsibleKey(Collapsible collapsible)
    {
        var sectionId = GetCollapsibleSectionId(collapsible);
        if (string.IsNullOrEmpty(sectionId))
            return null;

        if (collapsible.TryGetParentHandler<IGuidebookEntryAnchor>(out var anchor)
            && anchor.AnchorPrototype is { } anchorPrototype)
        {
            return $"{anchorPrototype.ID}|{sectionId}";
        }

        return sectionId;
    }

    private static string? GetCollapsibleSectionId(Collapsible collapsible)
    {
        for (var control = collapsible.Parent; control is not null; control = control.Parent)
        {
            if (!string.IsNullOrEmpty(control.Name))
                return control.Name;
        }

        var heading = GetCollapsibleHeading(collapsible);
        return heading?.Title ?? heading?.Label.Text;
    }
    // Reserve edit end: guide-book #320

    public void UpdateGuides(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries = null,
        ProtoId<GuideEntryPrototype>? forceRoot = null,
        ProtoId<GuideEntryPrototype>? selected = null)
    {
        // Reserve edit start: guide-book #323
        var keepPage = CanKeepCurrentPage(entries, rootEntries, forceRoot, selected);

        if (!keepPage)
        {
            _entries = entries;
            RepopulateTree(rootEntries, forceRoot);
            _treeRootEntries = rootEntries;
            _treeForceRoot = forceRoot;
            ClearSelectedGuide();
        }
        else
        {
            _entries = entries;
        }
        // Reserve edit end: guide-book #323

        Split.State = SplitContainer.SplitState.Auto;
        if (entries.Count == 1)
        {
            TreeBox.Visible = false;
            Split.ResizeMode = SplitContainer.SplitResizeMode.NotResizable;
            selected = entries.Keys.First();
        }
        else
        {
            TreeBox.Visible = true;
            Split.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
        }

        // Reserve edit start: guide-book #323
        if (keepPage)
        {
            EnsurePageVisible();
            SyncTreeSelection(selected);
            return;
        }
        // Reserve edit end: guide-book #323

        if (selected != null)
        {
            var item = Tree.Items.FirstOrDefault(x => x.Metadata is GuideEntry entry && entry.Id == selected);
            Tree.SetSelectedIndex(item?.Index);
        }
    }

    // Reserve edit start: guide-book #323
    private bool CanKeepCurrentPage(
        Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry> entries,
        List<ProtoId<GuideEntryPrototype>>? rootEntries,
        ProtoId<GuideEntryPrototype>? forceRoot,
        ProtoId<GuideEntryPrototype>? selected)
    {
        if (selected == null || _currentGuideEntry?.Id != selected)
            return false;

        if (EntryContainer.ChildCount == 0)
            return false;

        if (_entries.Count != entries.Count)
            return false;

        foreach (var key in entries.Keys)
        {
            if (!_entries.ContainsKey(key))
                return false;
        }

        if (_treeForceRoot != forceRoot)
            return false;

        return TreeRootsMatch(_treeRootEntries, rootEntries);
    }

    private static bool TreeRootsMatch(
        List<ProtoId<GuideEntryPrototype>>? a,
        List<ProtoId<GuideEntryPrototype>>? b)
    {
        if (a == null && b == null)
            return true;

        if (a == null || b == null)
            return false;

        return a.SequenceEqual(b);
    }

    private void EnsurePageVisible()
    {
        Placeholder.Visible = false;
        EntryContainer.Visible = true;

        if (_currentGuideEntry != null)
            SearchContainer.Visible = _currentGuideEntry.FilterEnabled;
    }

    private void SyncTreeSelection(ProtoId<GuideEntryPrototype>? selected)
    {
        if (selected == null || _currentGuideEntry?.Id != selected)
            return;

        ReturnContainer.Visible = _currentGuideEntry.RuleEntry;

        if (Tree.SelectedItem?.Metadata is GuideEntry entry && entry.Id == selected)
            return;

        var item = Tree.Items.FirstOrDefault(x => x.Metadata is GuideEntry e && e.Id == selected);
        _suppressSelectionReload = true;
        Tree.SetSelectedIndex(item?.Index);
        _suppressSelectionReload = false;
    }
    // Reserve edit end: guide-book #323

    private IEnumerable<GuideEntry> GetSortedEntries(List<ProtoId<GuideEntryPrototype>>? rootEntries)
    {
        if (rootEntries == null)
        {
            HashSet<ProtoId<GuideEntryPrototype>> entries = new(_entries.Keys);
            foreach (var entry in _entries.Values)
            {
                if (entry.Children.Count > 0)
                {
                    var sortedChildren = entry.Children
                        .Where(_entries.ContainsKey)
                        .Select(childId => _entries[childId])
                        .OrderBy(childEntry => childEntry.Priority)
                        .ThenBy(childEntry => Loc.GetString(childEntry.Name))
                        .Select(childEntry => new ProtoId<GuideEntryPrototype>(childEntry.Id))
                        .ToList();

                    entry.Children = sortedChildren;
                }

                entries.ExceptWith(entry.Children);
            }

            rootEntries = entries.ToList();
        }

        return rootEntries
            .Select(rootEntryId => _entries[rootEntryId])
            .OrderBy(rootEntry => rootEntry.Priority)
            .ThenBy(rootEntry => Loc.GetString(rootEntry.Name));
    }

    private void RepopulateTree(List<ProtoId<GuideEntryPrototype>>? roots = null,
        ProtoId<GuideEntryPrototype>? forcedRoot = null)
    {
        Tree.Clear();

        HashSet<ProtoId<GuideEntryPrototype>> addedEntries = new();

        var parent = forcedRoot == null ? null : AddEntry(forcedRoot.Value, null, addedEntries);
        foreach (var entry in GetSortedEntries(roots))
        {
            AddEntry(entry.Id, parent, addedEntries);
        }

        Tree.SetAllExpanded(true);
    }

    private TreeItem? AddEntry(ProtoId<GuideEntryPrototype> id,
        TreeItem? parent,
        HashSet<ProtoId<GuideEntryPrototype>> addedEntries)
    {
        if (!_entries.TryGetValue(id, out var entry))
            return null;

        if (!addedEntries.Add(id))
        {
            // TODO GUIDEBOOK Maybe allow duplicate entries?
            // E.g., for adding medicine under both chemicals & the chemist job
            _sawmill.Error($"Adding duplicate guide entry: {id}");
            return null;
        }

        var rulesProto = UserInterfaceManager.GetUIController<InfoUIController>().GetCoreRuleEntry();
        if (entry.RuleEntry && entry.Id != rulesProto.Id)
            return null;

        var item = Tree.AddItem(parent);
        item.Metadata = entry;
        var name = Loc.GetString(entry.Name);
        item.Label.Text = name;

        foreach (var child in entry.Children)
        {
            AddEntry(child, item, addedEntries);
        }

        return item;
    }

    private void HandleFilter()
    {
        if (Tree.SelectedItem != null && Tree.SelectedItem.Metadata is GuideEntry entry && entry.FilterEnabled)
        {
            var query = SearchBar.Text?.Trim() ?? string.Empty; // Reserve edit: guide-book #323
            var foundElements = EntryContainer.GetSearchableControls();

            foreach (var element in foundElements)
            {
                element.SetHiddenState(true, query);
            }
        }
    }
}
