// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client._Reserve.UserInterface.Systems.Ghost.Controls; // Reserve-Edit
using Content.Shared._Reserve.Antag;
using Content.Shared.Ghost;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        // Constants for UI dimensions
        private const int ButtonWidth = 180;
        private const int GridColumns = 5;
        private const float TooltipDelay = 0.1f;

        private string _searchText = string.Empty;

        // Reserve-Start
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private List<GhostWarpPlayer> _originalPlayerWarps = new();
        private List<GhostWarpPlace> _originalPlaceWarps = new();
        private List<GhostWarpGlobalAntagonist> _originalAntagonists = new();

        private List<GhostWarpPlayer> _playerWarps = new();
        private List<GhostWarpPlace> _placeWarps = new();
        private List<GhostWarpGlobalAntagonist> _globalAntagonists = new();

        private List<GhostWarpPlayer> _alivePlayers = new();
        private List<GhostWarpPlayer> _leftPlayers = new();
        private List<GhostWarpPlayer> _deadPlayers = new();
        private List<GhostWarpPlayer> _ghostPlayers = new();
        // Reserve-End

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            IoCManager.InjectDependencies(this); // Reserve
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        }

        public void Populate() // Reserve-Edit | UpdateWarps > Populate
        {
            // Reserve-Start
            GhostTeleportContainer.DisposeAllChildren();

            _playerWarps = _originalPlayerWarps;
            _placeWarps = _originalPlaceWarps;
            _globalAntagonists = _originalAntagonists;

            PlayersAllocation();
            AddButtons();
            // Reserve-End
        }

        public void UpdateWarps(List<GhostWarpPlayer> players, List<GhostWarpPlace> places, List<GhostWarpGlobalAntagonist> antagonists) // Reserve-Edit | Populate > UpdateWarps
        {
            // Reserve-Start
            _originalPlayerWarps = players.ToList();
            _originalPlaceWarps = places.ToList();
            _originalAntagonists = antagonists.ToList();

            Populate();
            // Reserve-End
        }

        private void AddButtons()
        {
            // Reserve-Start
            AddAntagButtons(_globalAntagonists, "ghost-teleport-menu-antagonists-label", "ButtonColorAntagonistDepartment");
            AddPlayerButtons(_alivePlayers, "ghost-teleport-menu-alive-label", string.Empty, true); // Alive
            AddPlayerButtons(_ghostPlayers, "ghost-teleport-menu-ghosts-label", string.Empty, true); // Ghost
            AddPlayerButtons(_leftPlayers, "ghost-teleport-menu-left-label", string.Empty, true); // Left
            AddPlayerButtons(_deadPlayers, "ghost-teleport-menu-dead-label", string.Empty, true); // Dead
            AddPlaceButtons(_placeWarps, "ghost-teleport-menu-locations-label", "ButtonColorUnknownDepartment");
            // Reserve-End
        }

        // Reserve-Start
        private void AddPlayerButtons(List<GhostWarpPlayer> players,
            string text,
            string styleClass,
            bool enableByDepartmentColorSheet)
        {
            if (players.Count == 0)
                return;

            var bigGrid = new GridContainer { HorizontalExpand = true }; // Reserve-Edit
            var header = CreateSectionHeader(text);
            bigGrid.AddChild(header);

            var sortedPlayers = SortPlayersByDepartment(players);

            foreach (var departmentList in sortedPlayers)
            {
                if (departmentList.Count == 0)
                    continue;

                var departmentGrid = new GridContainer
                {
                    Columns = GridColumns
                };

                var departmentPrototype = _prototypeManager.Index<DepartmentPrototype>(departmentList[0].DepartmentID);
                if (enableByDepartmentColorSheet)
                    styleClass = departmentPrototype.ButtonStyle;

                var labelText = departmentPrototype.Name;

                var departmentLabel = new Label
                {
                    Text = Loc.GetString(labelText) + ": " + departmentList.Count,
                    StyleClasses = { "LabelSecondaryColor" }
                };

                foreach (var player in departmentList)
                {
                    var playerButton = new ScrollingTextButton // Reserve-Edit
                    {
                        Text = player.Name,
                        TextAlign = Label.AlignMode.Right,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        SizeFlagsStretchRatio = 1,
                        StyleClasses = { styleClass },
                        ToolTip = player.JobName,
                        TooltipDelay = TooltipDelay,
                        SetWidth = ButtonWidth,
                    };

                    playerButton.OnPressed += _ => WarpClicked?.Invoke(player.Entity);

                    departmentGrid.AddChild(playerButton);
                }

                bigGrid.AddChild(departmentLabel);
                bigGrid.AddChild(departmentGrid);
            }

            GhostTeleportContainer.AddChild(bigGrid);
        }

        private void AddPlaceButtons(List<GhostWarpPlace> places, string text, string styleClass)
        {
            if (places.Count == 0)
                return;

            var bigGrid = new GridContainer { HorizontalExpand = true }; // Reserve-Edit
            var header = CreateSectionHeader(text);
            bigGrid.AddChild(header);

            var placesGrid = new GridContainer
            {
                Columns = GridColumns,
            };

            var countLabel = new Label
            {
                Text = Loc.GetString("ghost-teleport-menu-count-label") + ": " + places.Count,
                StyleClasses = { "LabelSecondaryColor" }
            };

            foreach (var place in places)
            {
                var placeButton = new ScrollingTextButton // Reserve-Edit
                {
                    Text = place.Name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    StyleClasses = { styleClass },
                    ToolTip = place.Description,
                    TooltipDelay = TooltipDelay,
                    SetWidth = ButtonWidth,
                };

                placeButton.OnPressed += _ => WarpClicked?.Invoke(place.Entity);

                placesGrid.AddChild(placeButton);
            }

            bigGrid.AddChild(countLabel);
            bigGrid.AddChild(placesGrid);

            GhostTeleportContainer.AddChild(bigGrid);
        }
        // Reserve-End

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            // Reserve-Edit-Start
            _searchText = args.Text.ToLower();

            GhostTeleportContainer.DisposeAllChildren();

            if (string.IsNullOrEmpty(_searchText))
            {
                _playerWarps = _originalPlayerWarps;
                _placeWarps = _originalPlaceWarps;
                _globalAntagonists = _originalAntagonists;
            }
            else
            {
                _playerWarps = GetSortedPlayers(_originalPlayerWarps).Where(p => p.Name.ToLower().Contains(_searchText)).ToList();
                _placeWarps = GetSortedPlaces(_originalPlaceWarps).Where(p => p.Name.ToLower().Contains(_searchText)).ToList();
                _globalAntagonists = GetSortedAntagonists(_originalAntagonists).Where(a => a.Name.ToLower().Contains(_searchText)).ToList();
            }
            PlayersAllocation();

            AddButtons();
            // Reserve-Edit-End
        }

        // Reserve-Start
        private void AddAntagButtons(List<GhostWarpGlobalAntagonist> antags, string text, string styleClass)
        {
            if (antags.Count == 0)
                return;

            var bigGrid = new GridContainer { HorizontalExpand = true }; // Reserve-Edit
            var header = CreateSectionHeader(text);
            bigGrid.AddChild(header);

            var sortedAntags = SortAntagsByWeight(antags);

            foreach (var antagList in sortedAntags)
            {
                if (antagList.Count == 0)
                    continue;

                var departmentGrid = new GridContainer
                {
                    Columns = GridColumns
                };

                var labelText = antagList[0].AntagonistName;

                foreach (var antag in antagList)
                {
                    var playerButton = new ScrollingTextButton // Reserve-Edit
                    {
                        Text = antag.Name,
                        TextAlign = Label.AlignMode.Right,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        SizeFlagsStretchRatio = 1,
                        StyleClasses = { styleClass },
                        ToolTip = Loc.GetString(antag.AntagonistDescription),
                        TooltipDelay = TooltipDelay,
                        SetWidth = ButtonWidth,
                    };

                    playerButton.OnPressed += _ => WarpClicked?.Invoke(antag.Entity);

                    departmentGrid.AddChild(playerButton);
                }

                var departmentLabel = new Label
                {
                    Text = Loc.GetString(labelText) + $": {antagList.Count}",
                    StyleClasses = { "LabelSecondaryColor" }
                };

                bigGrid.AddChild(departmentLabel);
                bigGrid.AddChild(departmentGrid);
            }

            GhostTeleportContainer.AddChild(bigGrid);
        }

        private Control CreateSectionHeader(string text, bool useStripeBack = true)
        {
            if (useStripeBack)
            {
                var stripe = new StripeBack { HorizontalExpand = true }; // Reserve-Edit
                var label = new Label
                {
                    Text = Loc.GetString(text),
                    StyleClasses = { "LabelBig" },
                    Align = Label.AlignMode.Center,
                    HorizontalExpand = true // Reserve-Add
                };
                stripe.AddChild(label);

                return stripe;
            }
            else
            {
                var label = new Label
                {
                    Text = Loc.GetString(text),
                    StyleClasses = { "LabelBig" },
                    Align = Label.AlignMode.Center,
                    HorizontalExpand = true // Reserve-Add
                };

                return label;
            }
        }

        public List<List<GhostWarpPlayer>> SortPlayersByDepartment(List<GhostWarpPlayer> players)
        {
            if (players.Count == 0)
                return new List<List<GhostWarpPlayer>>();

            return players
                .Where(p => _prototypeManager.TryIndex<DepartmentPrototype>(p.DepartmentID, out _))
                .GroupBy(p => _prototypeManager.Index<DepartmentPrototype>(p.DepartmentID).Weight)
                .OrderByDescending(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        public List<List<GhostWarpGlobalAntagonist>> SortAntagsByWeight(List<GhostWarpGlobalAntagonist> antagonists)
        {
            if (antagonists.Count == 0)
                return new List<List<GhostWarpGlobalAntagonist>>();

            return antagonists
                .Where(a => _prototypeManager.TryIndex<AntagonistPrototype>(a.PrototypeID, out _))
                .GroupBy(a => _prototypeManager.Index<AntagonistPrototype>(a.PrototypeID).Weight)
                .OrderBy(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        private List<GhostWarpPlace> GetSortedPlaces(List<GhostWarpPlace> places)
        {
            return places
                .OrderBy(w => w.Name)
                .ToList();
        }

        private List<GhostWarpPlayer> GetSortedPlayers(List<GhostWarpPlayer> players)
        {
            return players
                .OrderBy(w => w.Name)
                .ToList();
        }

        private List<GhostWarpGlobalAntagonist> GetSortedAntagonists(List<GhostWarpGlobalAntagonist> antagonists)
        {
            return antagonists
                .OrderBy(w => w.Name)
                .ToList();
        }

        private void PlayersAllocation()
        {
            _alivePlayers = _playerWarps.Where(warp => warp.IsAlive).ToList();
            _deadPlayers = _playerWarps.Where(warp => warp.IsDead).ToList();
            _leftPlayers = _playerWarps.Where(warp => warp.IsLeft).ToList();
            _ghostPlayers = _playerWarps.Where(warp => warp.IsGhost).ToList();
        }
        // Reserve-End
    }
}
