// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics; // Reserve edit: Fix language menu size
using Content.Client._EinsteinEngines.Language.Systems;
using Content.Shared._EinsteinEngines.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface; // Reserve edit: Fix language menu size
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._EinsteinEngines.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    // Reserve edit start: Fix language menu size
    private const float IconWidth = 32;
    private const float HeaderSeparation = 2;
    private const float RowPadding = 8;
    private const float WindowPadding = 64;
    private const float MinWindowWidth = 320;
    private const float DefaultWindowHeight = 300;

    [Dependency] private readonly ILocalizationManager _loc = default!;
    // Reserve edit end: Fix language menu size
    private readonly LanguageSystem _clientLanguageSystem;
    private readonly List<EntryState> _entries = new();

    public LanguageMenuWindow()
    {
        IoCManager.InjectDependencies(this); // Reserve edit: Fix language menu size
        RobustXamlLoader.Load(this);
        _clientLanguageSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _clientLanguageSystem.OnLanguagesChanged += UpdateState;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _clientLanguageSystem.OnLanguagesChanged -= UpdateState;
    }

    protected override void Opened()
    {
        UpdateState();
    }

    private void UpdateState()
    {
        var languageSpeaker = _clientLanguageSystem.GetLocalSpeaker();
        if (languageSpeaker == null)
            return;

        UpdateState(languageSpeaker.CurrentLanguage, languageSpeaker.SpokenLanguages);
    }

    public void UpdateState(ProtoId<LanguagePrototype> currentLanguage, List<ProtoId<LanguagePrototype>> spokenLanguages)
    {
        var langName = _loc.GetString($"language-{currentLanguage}-name"); // Reserve edit: Fix language menu size
        CurrentLanguageLabel.Text = _loc.GetString("language-menu-current-language", ("language", langName)); // Reserve edit: Fix language menu size

        OptionsList.RemoveAllChildren();
        _entries.Clear();

        foreach (var language in spokenLanguages)
        {
            AddLanguageEntry(language);
        }

        // Disable the button for the currently chosen language.
        foreach (var entry in _entries)
        {
            if (entry.Button != null)
                entry.Button.Disabled = entry.Language == currentLanguage;
        }

        ResizeToContent(); // Reserve edit: Fix language menu size
    }

    // Reserve edit start: Fix language menu size
    private void ResizeToContent()
    {
        CurrentLanguageLabel.InvalidateMeasure();
        CurrentLanguageLabel.Measure(Vector2Helpers.Infinity);
        var maxContentWidth = CurrentLanguageLabel.DesiredSize.X + RowPadding;

        foreach (var entry in _entries)
        {
            entry.NameLabel!.InvalidateMeasure();
            entry.NameLabel.Measure(Vector2Helpers.Infinity);
            entry.Button!.InvalidateMeasure();
            entry.Button.Measure(Vector2Helpers.Infinity);

            var rowWidth = IconWidth + HeaderSeparation
                + entry.NameLabel.DesiredSize.X + HeaderSeparation
                + entry.Button.DesiredSize.X + RowPadding;
            maxContentWidth = MathF.Max(maxContentWidth, rowWidth);
        }

        var titleWidth = MeasureFallbackLabelWidth(Title ?? string.Empty) + 80;
        var width = MathF.Max(MathF.Max(maxContentWidth + WindowPadding, titleWidth), MinWindowWidth);
        var height = MathF.Max(Size.Y, DefaultWindowHeight);

        MinSize = new Vector2(width, DefaultWindowHeight);
        SetSize = new Vector2(width, height);
    }

    private static float MeasureFallbackLabelWidth(string text)
    {
        var label = new Label { Text = text };
        label.Measure(Vector2Helpers.Infinity);
        return label.DesiredSize.X;
    }
    // Reserve edit end: Fix language menu size

    private void AddLanguageEntry(ProtoId<LanguagePrototype> language)
    {
        var proto = _clientLanguageSystem.GetLanguagePrototype(language);
        var state = new EntryState { Language = language };

        var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        #region Header
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 2
        };

        // Reserve edit start: Fix language menu size
        var name = new Label
        {
            Text = proto?.Name ?? _loc.GetString("generic-error"),
            VerticalAlignment = VAlignment.Center,
        };
        state.NameLabel = name;

        var spacer = new Control
        {
            HorizontalExpand = true,
            MinWidth = HeaderSeparation,
        };

        var button = new Button
        {
            Text = _loc.GetString("language-menu-select"),
            VerticalAlignment = VAlignment.Center,
        };
        button.OnPressed += _ => OnLanguageChosen(language);
        state.Button = button;

        header.AddChild(name);
        header.AddChild(spacer);
        header.AddChild(button);
        // Reserve edit end: Fix language menu size

        container.AddChild(header);
        #endregion

        #region Collapsible description
        var body = new CollapsibleBody
        {
            HorizontalExpand = true,
            Margin = new Thickness(4f, 4f)
        };

        var description = new RichTextLabel { HorizontalExpand = true };
        description.SetMessage(proto?.Description ?? _loc.GetString("generic-error")); // Reserve edit: Fix language menu size
        body.AddChild(description);

        var collapser = new Collapsible(_loc.GetString("language-menu-description-header"), body) // Reserve edit: Fix language menu size
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        container.AddChild(collapser);
        #endregion

        // Before adding, wrap the new container in a PanelContainer to give it a distinct look
        var wrapper = new PanelContainer();
        wrapper.StyleClasses.Add("PdaBorderRect");

        wrapper.AddChild(container);
        OptionsList.AddChild(wrapper);

        _entries.Add(state);
    }

    private void OnLanguageChosen(ProtoId<LanguagePrototype> id)
    {
        _clientLanguageSystem.RequestSetLanguage(id);

        // Predict the change
        if (_clientLanguageSystem.GetLocalSpeaker()?.SpokenLanguages is { } languages)
            UpdateState(id, languages);
    }

    private struct EntryState
    {
        public ProtoId<LanguagePrototype> Language;
        public Label? NameLabel; // Reserve edit: Fix language menu size
        public Button? Button;
    }
}
